anthropic.api.key=${ANTHROPIC_API_KEY:}

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=avlija;encrypt=false
spring.datasource.username=avlija_racuni
spring.datasource.password=MyPass@word
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8000

# run this on the server: keytool -genkeypair -alias avlija -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore avlija.p12 -validity 3650 -dname "CN=avlija"
server.ssl.enabled=true
server.ssl.key-store=avlija.p12
server.ssl.key-store-password=MyPass@word
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=avlija

# spring.mvc.static-path-pattern=/static/**
# spring.web.resources.static-locations=classpath:/static/

# Log all request mappings and handler resolutions
# logging.level.org.springframework.web=ERROR
# logging.level.org.springframework.boot.autoconfigure.web=ERROR

# Logging
# logging.level.root=ERROR
# logging.level.com.avlija=ERROR
# logging.file.name=logs/avlija.log
# logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
# logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n