anthropic.api.key=${ANTHROPIC_API_KEY}

# Azure SQL Database
spring.datasource.url=jdbc:sqlserver://avlija.database.windows.net:1433;databaseName=avlija;encrypt=true;trustServerCertificate=false;loginTimeout=30
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8000

# SSL for Spring Boot application
server.ssl.enabled=true
server.ssl.key-store=avlija.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=avlija